ufs-community/regional_workflow

jobs/JFV3CAM_SAR_CHGRES_FCSTBNDY
This pull request fixes two issues with the chgres_fcstbndy job.  The hour variable needs to be defined within the [if tmmark = tm00] construct because we do not want to create BCs for forecast hour 0 for the SAR without data assimilation.  In addition, bcfile.input needs to be deleted if it already exists.
=> Bug fixes to chgres fcstbndy J-job

scripts/exfv3cam_sar_fcst.sh, ush/global_chgres.sh
Eric R found a typo in the forecast run script.  Also, there were paths to fix files defined in the ush/global_chgres.sh script which should not be there.
=> Fix to forecast run script and remove fixed paths from chgres ush script

ush/setup.sh
- Update FV3SAR_DIR to accurately look into regional_workflow directory
structure
- The "write_tasks" check fixed to account for newer variable
"WRTCMP_write_tasks_per_group"
- Printf does not handle literal %'s well, need to include '%%' to get
a literal percent sign
=> Fixes to setup.sh:

Externals.cfg, modulefiles/regional_workflow/global_equiv_resol.cheyenne, modulefiles/regional_workflow/mosaic_file.cheyenne, modulefiles/regional_workflow/regional_grid.cheyenne, sorc/build_global_equiv_resol.sh, sorc/build_mosaic_file.sh, sorc/build_regional_grid.sh, sorc/global_equiv_resol.fd/Makefile_cheyenne, sorc/mosaic_file.fd/Makefile_cheyenne, sorc/regional_grid.fd/Makefile_cheyenne
Workflow runs to completion, these mods are non-answer changing:
nfiles_total = 82
nfiles_missing = 0
nfiles_different = 0
Final result of regression test:  PASS :)
Tested with
sorc/UFS_UTILS_develop head of dtc/develop branch
sorc/UFS_UTILS_chgres_grib2 hash c29174e
sorc/NEMSfv3gfs HEAD
sorc/EMC_post HEAD
=> - Modify Externals.cfg to use head of NCAR/UFS_UTILS dtc/develop branch

modulefiles/tasks/hera/run_post
This update allows the latest hash for post to run successfully on hera using the regional_workflow.
=> Update module load for hera to be consistent with what is in post repo

Externals.cfg
This includes updated modulefiles that will allow successful building of EMC_post on jet.
Running tests:
@JeffBeck-NOAA I am conducting the Hera and Cheyenne tests, but since I do not have access to Jet, can you confirm that this fixes the build problem you were seeing there?
=> Update EMC_post hash to top of DTC_post branch

ush/UFS_plot_domains.py, ush/set_predef_grid_params.sh, ush/valid_param_vals.sh
This replaces PR #132.  
Adding the pre-defined domains for HI, PR, and GU to set_predef_grid_params.sh, and adding JPgrid write component configuration for AK. 
The values for these domains have been taken from fix files generated for old output grid, originally located on Hera at /scratch4/NCEPDEV/fv3-cam/save/Benjamin.Blake/fix_fv3cam/fix_sar but have since been scrubbed. I archived a copy here: /scratch2/BMC/det/kavulich/fix/fix_sar
- This AK domain may be a somewhat duplicate of the "GSD_HRRR_AK_3km" domain; let me know if it should be omitted
-  I went with a pretty conservative number of nodes so currently all of these cases take a few hours to run. If the number of nodes should be increased let me know.
=> Add predefined hrrr domains to latest workflow

README.md, modulefiles/tasks/hera/make_grid, modulefiles/tasks/hera/make_ics.hardcoded, modulefiles/tasks/hera/make_ics.local, modulefiles/tasks/hera/make_lbcs.hardcoded, modulefiles/tasks/hera/make_lbcs.local, modulefiles/tasks/jet/make_grid, modulefiles/tasks/jet/make_ics.hardcoded, modulefiles/tasks/jet/make_ics.local, modulefiles/tasks/jet/make_lbcs.hardcoded, modulefiles/tasks/jet/make_lbcs.local
All the module files contained in this repository have been updated for the change on Jet/Hera to remove the contrib module, and instead use the `module use -a` method for locating necessary contrib package modulefiles. This will be the ONLY way to use these modules after June 11, 2020, and is already in place to work now. As such, this is a **time sensitive** PR.
Loaded a few different modules on front end node. This included modules that need to be loaded, and those "modules" that are actually shell scripts and must be sourced. Both methods worked as expected.
I did not run any workflow tests.
=> Fix for contrib module handling.

ush/templates/diag_table.FV3_GFS_2017_gfdlmp_regional
Bug fix:  Replace non-jinja placeholders in diag_table.FV3_GFS_2017_gfdlmp_regional with jinja-style placeholders.
Ran on hera the WE2E test configuration config.new_JPgrid.sh which uses the FV3_GFS_2017_gfdlmp_regional physics suite.  Passed the test. Probably no need to run tests on other machines.
=> Bug fix for diag_table.FV3_GFS_2017_gfdlmp_regional

ush/templates/FV3SAR_wflow.xml
Blank lines at the start of the rocoto XML apparently cause the rocoto commands to fail.  So, in this PR, we modify the rocoto XML template as follows:
1) Remove all blank lines at start.  
2) Put in a dash with jinja end-of-comment, i.e. change #} to -#}, for the jinja comment at the start of the template so that jinja doesn't leave an extra blank line after processing.
Conducted one WE2E test on hera.  Rocoto fails to start workflow without these changes, succeeds with.
=> Bug fix -- Remove blank lines at start of rocoto XML template.  

scripts/exregional_make_orog.sh, ush/config_defaults.sh, ush/setup.sh
Previously, in exregional_make_orog.sh, a local variable "topo_dir" was used as the location of the fix files for the make_orog task, and this variable was hard-coded as a path relative to the global "FIXgsm" variable. Now topo_dir is set as a global variable in setup.sh, just like FIXgsm and SFC_CLIMO_INPUT_DIR, to allow more flexibility for the location of these fixed input files.
In addition, all of these paths can now be directly specified by the user in config.sh, rather than needing to modify setup.sh every time you want to point to a new fix file location.
Ran a standard end-to-end case on Cheyenne (GSD_HRRR25km, 2019090118), and also ran the same test where I pointed to fixed data that I had copied to different directories via the config.sh file. These tests performed as expected. …
=> Make the location of the make_orog fix files more flexible

ush/generate_FV3SAR_wflow.sh
As it currently exists, the generate_FV3SAR_wflow.sh script can fail in some non-obvious ways if the correct python environment is not available. This PR adds some checks at the beginning of this script for the required python version and python modules that are needed to successfully set up the regional workflow, so the script will immediately fail with a descriptive error message if the necessary python environment is not available.
The error messaging is still not ideal, as the structure of this script does not allow for a simple exit upon error and still outputs some spurious error messages, but this is an improvement over the previous behavior in the case of a bad python environment.
Ran checks on Cheyenne, Jet, and Hera for the script's expected behavior. When the correct python …
=> Add check to generate_FV3SAR_wflow.sh for correct python environment

jobs/JREGIONAL_RUN_POST, scripts/exregional_run_post.sh, ush/Python/plot_allvars.py, ush/templates/FV3LAM_wflow.xml
Changes forecast hour precision from two to three digits, and adds an "f" prior to the forecast hour in the final grib2 file names.  Requested by GSL.  
Modifies the plot_allvars.py Python script to match this convention.
Tested successfully on Hera with both HRRR3km and HRRR25km domains.
@gsketefian
=> Change grib2 file name forecast hour precision from two to three digits

tests/baseline_configs/config.nco_GSD_HRRR25km_HRRRX_RAPX.sh, tests/baseline_configs/config.nco_GSD_SUBCONUS3km_HRRRX_RAPX.sh, tests/baselines_list.txt, ush/set_predef_grid_params.sh, ush/setup.sh, ush/valid_param_vals.sh
* Add new subconus 3km grid of ESGgrid type named GSD_SUBCONUS3km.
* Allow this as well as the GSD_HRRR25km, GSD_HRRR13km, and GSD_RAP13km grids to run in NCO mode.
* Add new WE2E test for the GSD_SUBCONUS3km grid in NCO mode named nco_GSD_SUBCONUS3km_HRRRX_RAPX.
* Add new WE2E test for the GSD_HRRR25km grid in NCO mode named nco_GSD_HRRR25km_HRRRX_RAPX.
Ran the two new WE2E tests on hera -- nco_GSD_SUBCONUS3km_HRRRX_RAPX and nco_GSD_HRRR25km_HRRRX_RAPX.  Both completed successfully.  The changes do not affect any of the other WE2E tests, so those were not run.
=> Add new subconus 3km predefined grid; add WE2E tests for this and the GSD_HRRR25km grid.

scripts/exregional_make_grid.sh, scripts/exregional_make_ics.sh, scripts/exregional_make_lbcs.sh, scripts/exregional_make_orog.sh, scripts/exregional_run_post.sh, ush/generate_FV3LAM_wflow.sh, ush/setup.sh
The new top-level cmake build for the SRW App ([SRW App PR#27](https://github.com/ufs-community/ufs-srweather-app/pull/27)) results in some executables having different names. This PR makes modifications that
1. Allow the workflow to run successfully with the new cmake build and its different executable names, and
2. Allow back-compatibility with the old build system to allow for a gradual transition to new build system
This PR also explicitly disallows running the workflow without CCPP, which we decided against supporting several months ago. I don't think the capability even works so this shouldn't effect anyone at this time.
- **Cheyenne**: Build and end-to-end test ("DOT_OR_USCORE" test case) was successful on Cheyenne with intel, both for the cmake build and the old build script (that …
=> Modifications to run workflow with unmodified executable names from each repository

ush/generate_FV3LAM_wflow.sh
=> Add NOMADS script call back into generate script.

scripts/exregional_make_grid.sh, scripts/exregional_make_orog.sh, scripts/exregional_make_sfc_climo.sh, ush/setup.sh
This pull request contains changes that are needed for running the latest version of the regional workflow on WCOSS.  It involves modifications to the make_grid, make_orog, and make_sfc_climo ex-scripts, and setup.sh.  There are some additional modifications required to the xml template and modulefiles, but we can discuss how to best handle those changes at a later date.  This PR needs to be tested concurrently with PR #31 of ufs-srweather-app.
Successfully completed an end-to-end test on the WCOSS-Dell with these changes.
Annette Gibbs was a huge help with running these tests on WCOSS.
=> Changes needed to run the regional workflow on WCOSS

scripts/exregional_run_fcst.sh, ush/generate_FV3LAM_wflow.sh, ush/set_ozone_param.sh, ush/set_thompson_mp_fix_files.sh, ush/setup.sh
Add and call a function that checks for use of Thompson microphysics parameterization in the suite definition file (SDF).  If not, do nothing.  If so, add to the appropriate workflow arrays the names and other associated values of the fixed files needed by this parameterization so that they are automatically copied and/or linked to instead of being regenerated from scratch in the run_fcst task.
On hera, ran two WE2E tests, one in NCO mode (nco_RRFS_CONUS_25km_HRRRX_RAPX) and the other in community mode (suite_FV3_GSD_v0).  These use suites FV3_GSD_SAR and FV3_GSD_v0, respectively, and both of these call Thompson microphysics.  Both succeeded.
This PR resolves issue #297.
=> Add capability to link to specific fix files when using Thompson microphysics (so they don't have to be regenerated)

scripts/exregional_make_orog.sh, scripts/exregional_run_fcst.sh, tests/run_experiments.sh, ush/config_defaults.sh, ush/link_fix.sh, ush/setup.sh, ush/templates/FV3.input.yml
Removed checks on the RRFS_v1beta SDF implemented for use with the GSL GWD suite (now uses the GFS GWD suite).  No longer copies staged orography files necessary for the GSL GWD suite.
End-to-end runs DOT_OR_USCORE, suite_FV3_GFS_v15p2, and suite_FV3_RRFS_v1beta succeeded on Cheyenne.
Related to https://github.com/NOAA-EMC/regional_workflow/pull/322
Original author: JeffBeck-NOAA <jeff.beck@noaa.gov>
=> Apply PR #322 to develop

ush/set_thompson_mp_fix_files.sh
Add an if statement in set_thompson_mp_fix_files.sh to source Thompson climo file from $FIXgsm when using a combination of a Thompson-based SDF and non-RAP/HRRR external model data.  This will allow the user to correctly initialize the ice- and water-friendly aerosols when they are unavailable in the external model files.
Tested end-to-end run on Jet.
@gsketefian
=> Add Thompson ice- and water-friendly aerosol climo file support

ush/fill_jinja_template.py, ush/launch_FV3LAM_wflow.sh, ush/templates/FV3LAM_wflow.xml
Changes in #339 broke the jinja templating script for creating the workflow xml on platforms that do not have "partition_default", "partition_hpss", or "partition_fcst" settings. Basically it boils down to platforms whose job scheduler does not support the rocoto "partition" tag. Cheyenne is one of these platforms.
Additionally, this PR specifies the location of the new rocoto module on cheyenne, so tests can now be launched from a cron job on Cheyenne.
Ran a small set of end-to-end tests on Cheyenne (intel) successfully with no failures: DOT_OR_USCORE, grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2, suite_FV3_GFS_v15p2, and suite_FV3_RRFS_v1beta (test location: /glade/scratch/kavulich/UFS_CAM/testing/rocoto_on_cheyenne/expt_dirs)
Ran a full suite of tests on Hera to ensure …
=> Allow running from crontab on Cheyenne, as well as fix workflow generation on Cheyenne

ush/valid_param_vals.sh
Since only FV3_GFS_v15p2 and FV3_RRFS_v1beta CCPP suites are supported for the UFS release, this PR removes all other suites from valid_param_vals.sh on the release branch. 
This change should *only* be applied to the release branch; we will need a more elegant solution for the develop branch to keep up with CCPP suite changes going forward.
When I attempted to run a test with an unsupported suite, the workflow generation script now fails as expected.
This change only impacts the workflow generation, but as a sanity check I also ran a build test on Hera, and ran the following end-to-end tests which completed successfully:
- grid_RRFS_CONUS_25km_ics_HRRRX_lbcs_RAPX_suite_RRFS_v1beta
=> Remove all but supported CCPP suites from valid_param_vals.sh

ush/generate_FV3LAM_wflow.sh
The develop branch of ufs-weather-model was updated a couple months ago so that the weather model is no longer built as "NEMS.exe" (https://github.com/ufs-community/ufs-weather-model/pull/217). The workflow generation script needs to be updated with the new model executable name: ufs_model. 
This PR will need to be merged in order to use regional_workflow and the ufs-srweather-app with the most up-to-date develop branch of ufs-weather-model. A PR will be upcoming to update ufs-srweather-app to point to this hash once this PR is merged.
Ran generation script successfully with fully updated workflow.
This is necessary (but not sufficient) in order to resolve https://github.com/ufs-community/ufs-srweather-app/issues/57
=> Update weather model executable name

ush/fill_jinja_template.py, ush/launch_FV3LAM_wflow.sh, ush/templates/FV3LAM_wflow.xml
A fix was applied to the release branch for the Cheyenne workflow and automated testsing in #343, this PR applies the same to develop.
Workflow built and ran on Cheyenne; the following tests were run and all passed:
Fully resolves #326
=> Cherry-picking #343 to fix cheyenne workflow

modulefiles/tasks/cheyenne/make_grid.local, modulefiles/tasks/cheyenne/make_ics.local, modulefiles/tasks/cheyenne/make_lbcs.local, modulefiles/tasks/cheyenne/run_fcst.local, tests/run_experiments.sh, ush/set_extrn_mdl_params.sh, ush/setup.sh
A few updates are needed to the static input and environment setup files for the SRW on Cheyenne. The static files are now located under the `/glade/p/ral/jntp/UFS_SRW_app/` directory rather than the `/glade/p/ral/jntp/UFS_CAM` directory to conform with the latest naming conventions. The python environment has also been renamed to "regional_workflow" to conform with the naming convention of the conda environments on NOAA HPC platforms.
Ran the release suite of end-to-end tests (`tests/testlist.release_public_v1.txt`) and all passed. A few of these were actually previously broken on Cheyenne, and now run to completion successfully.
The only changes here are to Cheyenne-specific code, but I also ran the release suite on Hera as a sanity check (all passed).
=> Updates to static file structure and naming on Cheyenne.

ush/load_modules_run_task.sh
The script 'load_modules_run_task.sh' in the 'regional_workflow/ush' directory is modified to change the file names of the 'README_[machine].txt' files.
The modified one was tested on the WCOSS Dell and Cray as well as on Hera.
- Fixes the issue mentioned in #407.
- Dependency:  https://github.com/ufs-community/ufs-srweather-app/issues/88
=> release/public-v1: modify 'ush/load_modules_run_task.sh' to change the file names of README.txt in the SRW App

scripts/exregional_make_ics.sh, scripts/exregional_make_lbcs.sh, ush/check_ruc_lsm.sh, ush/generate_FV3LAM_wflow.sh, ush/set_thompson_mp_fix_files.sh, ush/setup.sh
PR #[94](https://github.com/ufs-community/ufs-srweather-app/pull/94) into ufs-srweather-app should be merged right after this PR.
* Add the new function check_ruc_lsm.sh that reads in the SDF to check whether it uses the RUC LSM.  If so, it sets the local variable sdf_uses_ruc_lsm to "TRUE", otherwise to "FALSE".  It then sets the environment variable whose name is specified by the input argument output_varname_sdf_uses_ruc_lsm to the value of sdf_uses_ruc_lsm.
* In setup.sh, introduce new workflow variable SDF_USES_RUC_LSM by passing its name as an argument to the new function check_ruc_lsm.sh.  This gets set to "TRUE" if the physics suite uses the RUC LSM and "FALSE" otherwise.
* In exregional_make_ics.sh, set the chgres_cube namelist variable nsoill_out (which is the number of soil …
=> Improve the way LSM-related parameters are set.

ush/launch_FV3LAM_wflow.sh, ush/setup.sh
Added sourcing of bash utilities to avoid $SED undefined variable error when using the workflow launch script.  Add Rocoto as the workflow manager on Gaea.
Tested on Gaea.
@climbfuji, @mkavulich, @gsketefian
=> release/public-v1: bash utilities fix for workflow launch script and add Rocoto as Gaea workflow manager

modulefiles/tasks/gaea/make_grid.local, modulefiles/tasks/gaea/make_ics.local, modulefiles/tasks/gaea/make_lbcs.local, modulefiles/tasks/gaea/run_fcst.local
Remove setting PS1 from modulefiles/tasks/gaea/*.local
The miniconda3 `profile.sh` on gaea script was fixed as suggested by @mkavulich, and setting `PS1` in the task modulefiles is no longer required on gaea.
See https://github.com/ufs-community/ufs-srweather-app/pull/101
https://github.com/ufs-community/ufs-srweather-app/pull/101
=> release/public-v1: Remove setting PS1 from modulefiles/tasks/gaea/*.local

ush/setup.sh
It was found that if set -u is in the user's default bash environment, this will cause the launch script or individual run scripts to fail because you're using a variable before it's defined; this is likely to occur if you submit any of these scripts from a crontab. This was due to the way that the default run command was set up for MacOS and generic LINUX platforms, which was a bit of a hack that resulted in RUN_CMD_FCST being defined twice in var_defns.sh. The fix will delete the first instance of RUN_CMD_FCST in var_defns.sh so that it is no longer referencing an undefined variable early on.
This potential bug does not affect Tier 1 supported platforms, only MacOS and generic Linux.
Tested on affected MacOS platform and the fix worked. Also ran end-to-end tests on Hera and Cheyenne …
=> Remove the first instance of "RUN_CMD_FCST" in var_defns.sh to avoid potential undefined variable issues

ush/launch_FV3LAM_wflow.sh
The 'module purge' command is added to the launch script 'launch_FV3LAM_wflow.sh' to avoid a module conflict on Orion.
The tasks are submitted without any conflicts on Orion.
Fixes issue mentioned in #436
=> Add 'module purge' to launch script for Orion

modulefiles/tasks/gaea/make_grid.local, modulefiles/tasks/gaea/make_ics.local, modulefiles/tasks/gaea/make_lbcs.local, modulefiles/tasks/gaea/run_fcst.local, ush/load_modules_run_task.sh
Update gaea task module files and `ush/load_modules_run_task.sh` to avoid using the lua module environment.
See https://github.com/ufs-community/ufs-srweather-app/pull/107 for testing.
=> Update of gaea environment to not use lua modules

ush/wrappers/README.md
The README.md file for the stand-alone wrapper scripts had the wrong name for the workflow generation script. Thanks to @climbfuji for pointing out this error.
none needed
=> Correct name of workflow generation script in README.md for stand-alone scripts

ush/setup.sh
Update the FIXgsm (fix_am) directory for Gaea.
Tested on Gaea with a 3-km domains using the RRFS_v1alpha SDF.
=> Modify FIXgsm path for Gaea.

scripts/exregional_make_ics.sh, scripts/exregional_make_lbcs.sh, scripts/exregional_make_sfc_climo.sh, scripts/exregional_run_fcst.sh, scripts/exregional_run_post.sh
The scripts are using the wrong MPI launcher on Jet.
On Jet, some MPI programs will freeze forever if run within srun (especially with large jobs) which is why the admins suggest mpirun. This happened for me when running the workflow on Jet. Nobody has tracked down the cause of this Jet SLURM bug, so it might depend on the user account; I can't know. However, it is 100% reproducible for the same job in the same account. The global workflow, and parts of the RAPX and HRRRX workflow, use mpirun; so does JET.env. The regional_workflow should follow the admin recommendations too, so the workflow will run in all accounts with all job sizes.
All jobs will use "APRUN=mpirun...", copied from the "CHEYENNE" block. For the sfc_climo job, it looks like this:
```
"JET")
nprocs=$(( …
```
=> Use mpirun instead of srun on Jet to avoid jobs freezing when starting MPI programs.

ush/templates/FV3.input.yml
As described in PR https://github.com/NOAA-EMC/regional_workflow/pull/451 for the release branch, all the `fdiag' entries are removed from 'ush/templates/FV3.input.yml' on the develop branch.
Graduate Student Test (CONUS 25km, FV3_GFS_v15p2):
- Before: **step** shape (every three in a row) in 12-24hr, and constant after 24hr
- After: smooth curve (no same values over the period)
- Fixes issue mentioned in #453.
- Related to PR https://github.com/NOAA-EMC/regional_workflow/pull/451
=> Fix the 'fdiag' issue on the develop branch

ush/config_defaults.sh
- Add the global CO2 historical data for the last three years (2019-2021) to the list in 'config_default.sh'.
- Completed the GST test successfully.
- The three files are copied and linked in the experimental directory.
Fixes issue mentioned in #476
@EricRogers-NOAA
=> Add last three year global CO2 historical data

.github/PULL_REQUEST_TEMPLATE
Updated the PR template file (.github/PULL_REQUEST_TEMPLATE) to request the branch name be included in the title and supporting documentation also be included (in the ufs-srweather-app repo) with a PR for new capabilities.
None required.
=> Update PR template for branch and documentation [to develop]

tests/run_experiments.sh
Path to staged data for the Cheyenne end-to-end tests was incorrect.
Subset of WE2E tests run on Cheyenne and all succeeded:
GST_release_public_v1
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
No changes necessary
Fixes issue mentioned in #464
@jwolff-ncar
=> Fix path to staged data for WE2E tests on Cheyenne

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE
* Add dependencies section to existing PR template
* Add templates for bug and feature issues
* This will provide better guidance for developers on what information to provide when submitting an issue or PR, and allow better organization/prioritization of PRs and issues for code management.
* See: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates
None required
None required
=> Add issue templates

ush/set_thompson_mp_fix_files.sh
- A recent update on Thompson scheme requires additional FIX files: `qr_acr_qgV2.dat` and `qr_arc_qsV2.dat`.
- The two files are added to the list of `thompson_mp_fix_files` in `ush/set_thompson_mp_fix_files.sh`.
- The two files have been added to the the `FIXgsm` directory on Hera, WCOSS dell and cray, Orion, Jet, and RZDM.
- It was confirmed that the new two files were copied to the `fix_am` directory by running `generate_FV3LAM_wflow.sh`.
- Fixes issue mentioned in #497 
@JiliDong-NOAA, @KateFriedman-NOAA
=> Add new FIX files for recent update on Thompson scheme

ush/config_defaults.sh, ush/launch_FV3LAM_wflow.sh, ush/setup.sh
- The name of the base directory of the external source code for the forecast model is parameterized in 'ush/setup.sh'.
- Its default value is 'ufs_weather_model' in 'ush/config_defaults.sh' and it can be specified in 'ush/config.sh'.
- Update the version of Rocoto for the WCOSS dell and cary.
WE2E Tests on Hera:
- grid_RRFS_NA_13km
- grid_RRFS_NA_3km
Fixes issue mentioned in #503
=> Parameterize name of forecast model in ush/setup.sh

ush/config_defaults.sh
Change the underscores in the name of the ufs weather model (ufs_weather_model) to dashes (ufs-weather-model) in 'config_default.sh' to match it with the name of the authoritative repository.
- GST test on the WCOSS dell
- https://github.com/ufs-community/ufs-srweather-app/pull/146
- Fixes issue mentioned in #505 
- Related to https://github.com/ufs-community/ufs-srweather-app/issues/145
=> Make the name of the forecast model the same as its repository

ush/config_defaults.sh, ush/generate_FV3LAM_wflow.sh, ush/setup.sh, ush/templates/FV3LAM_wflow.xml, ush/valid_param_vals.sh
Since the latest version of the ufs weather model has the in-line post option ('write_dopost' in model_configure), a flag turning on/off the 'run_post' task is added to the workflow template.
GST test for 6h forecast on the wcoss dell
Fixes issue mentioned in #509
=> Add a flag turning on/off the 'run_post' task in the workflow template

ush/launch_FV3LAM_wflow.sh
- An array index of 'cycle_statue' was missing in the conditional statement of the launch script (launch_FV3LAM_wflow.sh).
- An array index is added to 'cycle_status'.
Fixes issue mentioned in #512
=> Fix the array index issue on cycle_staus in the launch script

ush/get_extrn_mdl_file_dir_info.sh
Add "atmos" to the HPSS path for FV3GFS data after March 20th, 2021.
Tests one day before an after the change on Hera.
This resolves Issue #514.
=> Add /atmos to HPSS path for GFS grib2 files after certain date

ush/launch_FV3LAM_wflow.sh, ush/templates/FV3LAM_wflow.xml
This PR bundles together two bug fixes:
1) There is a missing index for an array in the launch script launch_FV3LAM_wflow.sh that causes the script to work incorrectly when more than one cycle is being run.  Add the missing index.  Note that this was fixed in the develop branch via PR #513.
2) There is a missing jinja2 if-statement in the template file FV3LAM_wflow.xml that causes the workflow generation script generate_FV3LAM_wflow.xml to fail.  This was caused by commit #[57c2aed](https://github.com/NOAA-EMC/regional_workflow/commit/57c2aed40cb1e9ee07812078027787fb5bde6d98) (without a PR?) into the RRFS_baseline branch.  Add the missing if-statement.
* No test was conducted for the bug in launch_FV3LAM_wflow.sh.  Assuming that the tests conducted for PR #513 are sufficient.
* A workflow …
=> Bug fixes for workflow xml template and launch script

modulefiles/tasks/wcoss_dell_p3/run_vx.local, ush/templates/FV3LAM_wflow.xml
- Since the version of MET was updated to 10.0 on Hera, its version on WCOSS are updated to 10.0.0.
- Since some verification tasks in the workflow template were modified from hpss queue to default queue, some commands only for the WCOSS dell and cray in the corresponding tasks are removed.
GST + verification on the wcoss dell
Fixes issue mentioned in #534.
Related to PR https://github.com/NOAA-EMC/regional_workflow/pull/528.
=> Update met version and workflow template for WCOSS

scripts/exregional_make_grid.sh, scripts/exregional_run_fcst.sh, ush/create_diag_table_file.sh, ush/generate_FV3LAM_wflow.sh, ush/setup.sh
This PR creates the diag_table file during the forecast task instead of when the grid generation script is run.  It contains the same changes as PR#349, but includes the compromise solution for ALL_CDATES based on the size of NUM_CYCLES.
Tested on Hera with single and multiple cycles to ensure proper creation of diag_table files and ALL_CDATES information in var_defns.sh as a function of NUM_CYCLES.
=> Changes required to produce the diag_table file at forecast run time.

scripts/exregional_run_fcst.sh
- Modify the file conversion part in the run_fcst script to change the number of digits from 2 to 3.
- When FCST_LEN_HRS<100, output files have 2 digit hours.
- When FCST_LEN_HRS>=100, output files have 3 digit hours.
- 120 hour forecast run (WRITE_DOPOST="TRUE", FCST_LEN_HRS="120")
- Fixes issue mentioned in #548
=> Fix file conversion issue on inline post with 3 digit forecast

modulefiles/tasks/hera/make_grid.local, modulefiles/tasks/hera/make_ics.local, modulefiles/tasks/hera/make_lbcs.local, modulefiles/tasks/hera/run_fcst.local, modulefiles/tasks/jet/make_grid.local, modulefiles/tasks/jet/make_ics.local, modulefiles/tasks/jet/make_lbcs.local, modulefiles/tasks/jet/run_fcst.local, modulefiles/tasks/orion/make_grid.local, modulefiles/tasks/orion/make_ics.local, modulefiles/tasks/orion/make_lbcs.local, modulefiles/tasks/orion/run_fcst.local, ush/load_modules_run_task.sh
This PR addresses an error that occurs at run time ```ModuleNotFoundError: No module named 'f90nml'```. A similar error may appear in any of the tasks that use a conda environment, and could potentially list `jinja2` instead.
The version of lmod on Hera was updated. The behavior of the `system` command has changed and now runs only in a subshell. As an lmod-version-independent fix, the module will no longer activate a conda environment, but will set the conda environment that should be activated through an environment variable, then the script will activate any required conda environment. 
Note: Users who do not run with Rocoto, but still use these modules, will have an extra step of activating the environment manually.
I built and ran a single WE2E test successfully on Hera with these …
=> Update syntax for latest version of lmod.

scripts/exregional_make_orog.sh
Remove "refine_ratio = ${refine_ratio}" in scripts/exregional_make_orog.sh to fix filter_topo failure
regional ESG grids/topography
Fixes issue mentioned in #546
=> change input.nml for filter topo to fix task failure

scripts/exregional_run_fcst.sh, ush/generate_FV3LAM_wflow.sh, ush/setup.sh
The NEMS driver now requires fd_nems.yaml file. This change will copy field dictionary file from tests/parm into exptdir during generate workflow. Then Link field dictionary file into run_dir during run forecast. The change requires updates to the ufs-weather-model, which contains the fd_nems.yaml file in tests/parm directory.
6 hour simulation using community run environment on Jet with RRFS_CONUS_3km grid and FV3_RRFS_v1beta ccpp physics suite. The run did not produce bit-for-bit results but this is likely due to the upgraded ufs-weather-model.
Add any links to external PRs. For example:
- https://github.com/ufs-community/ufs-weather-model (3b8bb78642f989d4e81e0975553285095667cc97)
- Updates to environment to support updated ufs-weather-model (incomplete). Each env file needs to be …
=> Copy and link NEMS field dictionary file

scripts/exregional_run_fcst.sh
PR #349 (via PR #533) moves diag_table creation from the grid generation step to the run_fcst portion of the workflow.  However, it also uses the "run_dir" location instead of "cycle_dir" as the target for the diag_table file.  While these two locations are identical for deterministic simulations, they are not the same when using the ensemble mode (due to member directories).  Therefore, the diag_table file should no longer be symbolically linked from the "cycle_dir" location to the "run_dir" directory in ensemble mode (the file is now copied directly to "run_dir" for each ensemble member).
Successfully ran a deterministic and two-member ensemble simulation on Hera.
=> Remove symbolic linking of diag_table when running in ensemble mode.

ush/config.community.sh, ush/config.nco.sh
Just to make it clear that this must be changed if using a compiler other than Intel.
No testing necessary, since this is just putting the COMPILER value from ``config_defaults.sh`` into the ``config.*.sh`` files.
None
This is in the documentation for the UFS SRW App develop branch.
=> Add COMPILER="intel" to config.community.sh and config.nco.sh

ush/templates/FV3.input.yml
Removes the update of 'domains_stack_size' (3000000 -> 1800200) in FV3.input.yml to avoid mpp_domains_stack overflow in a high-resolution domain (RRFS_NA_3km).
WE2E tests on Hera:
- grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
- grid_RRFS_NA_3km
Fixes issue mentioned in #557 
@BenjaminBlake-NOAA
=> Remove update of domains_stack_size from FV3.input.yml

scripts/exregional_make_grid.sh, ush/config_defaults.sh, ush/set_gridparams_ESGgrid.sh, ush/set_predef_grid_params.sh, ush/setup.sh, ush/templates/regional_grid.nml
Add the pazi parameter as a definable option to the workflow to allow for its addition to the regional_esg_grid namelist.  Set pazi to -13.0 for the RRFS_NA_3km domain to obtain the proper grid rotation angle.
Test on Hera with the RRFS_NA_3km domain and with the RRFS_CONUS_3km domain, the latter of which does not have a rotation angle, but is correctly set to pazi=0.0.
Added in-line comments to explain the pazi parameter.
Resolves Issue #566.
@BenjaminBlake-NOAA, @JacobCarley-NOAA, @gsketefian
=> Add the pazi parameter option to the creation of the regional_esg_grid namelist; set pazi=-13.0 for the RRFS_NA_3km domain

scripts/exregional_make_orog.sh
fix filter_topo failure when GWD orog is on 
The changes have been tested for make_orog and it is confirmed to fix the filter_topo failure 
This PR is for Issue #568 
If this PR is contributing new capabilities that need to be documented, please also include updates to the RST files in the ufs-srweather-app repository (docs/UsersGuide/source) as supporting material.
If this PR is resolving or referencing one or more issues, in this repository or elewhere, list them here. For example, "Fixes issue mentioned in #123" or "Related to bug in https://github.com/NOAA-EMC/other_repository/pull/63"
If others have contributed to this work aside from the PR author, list them here
=> fix filter_topo failure when GWD orog is on

tests/WE2E/run_WE2E_tests.sh
- Add the parameters for MET on WCOSS to the 'run_WE2E_tests.sh' script of WE2E.
- Update the directory structure of the user-staged external FV3GFS data on Hera.
MET_verification test of WE2E on the wcoss dell and cray as well as Hera.
Fixes issue mentioned in #573
=> Set up the parameters for MET on WCOSS in run_WE2E_tests.sh

modulefiles/tasks/cheyenne/run_vx.local, tests/WE2E/run_WE2E_tests.sh
Added ability to run verification tasks on Cheyenne by including a new modulefiles/tasks/cheyenne/run_vx.local. Also updated the WE2E test to run the MET_verification configuration on Cheyenne.
On Cheyenne:
PREDEF_GRID_NAME="RRFS_CONUS_25km"
CCPP_PHYS_SUITE="FV3_GFS_v15p2"
FCST_LEN_HRS="36"
LBC_SPEC_INTVL_HRS="3"
DATE_FIRST_CYCL="20190615"
DATE_LAST_CYCL="20190615"
CYCL_HRS=( "00" )
EXTRN_MDL_NAME_ICS="FV3GFS"
EXTRN_MDL_NAME_LBCS="FV3GFS"
FV3GFS_FILE_FMT_ICS="grib2"
FV3GFS_FILE_FMT_LBCS="grib2"
MODEL="FV3_GFS_v15p2_CONUS_25km"
METPLUS_PATH="/glade/p/ral/jntp/MET/METplus/METplus-4.0.0"
MET_INSTALL_DIR="/glade/p/ral/jntp/MET/MET_releases/10.0.0"
CCPA_OBS_DIR="/glade/p/ral/jntp/UFS_SRW_app/develop/obs_data/ccpa/proc"
MRMS_OBS_DIR="/glade/p/ral/jntp/UFS_SRW_app/develop/obs_data/mrms/proc" …
=> Port verification tasks to run on Cheyenne

scripts/exregional_run_fcst.sh, scripts/exregional_run_post.sh, ush/config_defaults.sh, ush/setup.sh
Since the repository name of post-processing was changed from 'EMC_post' to 'UPP', the external name and prefix for post-processing is changed from 'EMC_post' to 'UPP'.
WE2E tests on WCOSS_DELL_P3:
- MET_verification
- https://github.com/ufs-community/ufs-srweather-app/pull/171
Fixes issue mentioned in #589
=> 'EMC_post' is changed to 'UPP'

tests/WE2E/run_WE2E_tests.sh
The WE2E tests fail due to the undeclared variables 'RUN_TASK_VX_ENSGRID' and 'RUN_TASK_VX_ENSPOINT' in 'run_WE2E_tests.sh'. Since these two variables are not used in the regional workflow yet, they are removed from the script.
WE2E test:
- MET_verification
Fixes issue mentioned in #591
=> Remove unbound variables from run_WE2E_tests.sh

modulefiles/tasks/wcoss_cray/run_vx.local, tests/WE2E/run_WE2E_tests.sh
The version of MET/METplus in the WE2E script is updated to the latest for the WCOSS Cray.
WE2E 'MET_verification' test on the WCOSS Cray
Fixes issue mentioned in #594
=> Update MET/METplus in WE2E for WCOSS Cray

ush/Python/environment.yml
This addition should allow a user to install their own pygraf conda environment for platforms that are not supported. It is identical (currently) to the one included in the https://github.com/NOAA-GSL/pygraf repo.
It is used regularly in our CI/CD tests.
I am unsure where/if this type of activity is included in the docs. I'd be happy to add a few lines on this file if someone could point me to the best place for it.
=> Adding an environment file for installing pygraf.

scripts/exregional_make_ics.sh, scripts/exregional_make_lbcs.sh, scripts/exregional_make_orog.sh, scripts/exregional_run_fcst.sh, ush/config_defaults.sh, ush/launch_FV3LAM_wflow.sh, ush/load_modules_run_task.sh, ush/setup.sh, ush/templates/FV3LAM_wflow.xml
This modification allows for a user to run with Rocoto on their own Linux-based platform, which still requires modules to be installed. 
Ran with the corresponding linux_target branch on Hera. Passed the grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GSD_SAR. 
Tests for the new functionality were conducted on the RRFS Cloud AWS platform and within a Docker container. Currently no additional test was added to the test framework for this capability since we have no intent on supporting any defined linux configuration.
- https://github.com/ufs-community/ufs-srweather-app/pull/184
I will need guidance on where and how to add documentation for this addition, if it is necessary.
This PR addresses PR #610 
@christopherwharrop-noaa
=> Add support for Rocoto with generic LINUX platform

scripts/exregional_make_grid.sh, scripts/exregional_make_ics.sh, scripts/exregional_run_post.sh, tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_NA_3km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1alpha.sh
To resolve the memory issue, 'ulimit' is added to the 'make_grid', 'make_ics', and 'run_post' scripts for Orion.
WE2E tests on Orion and Hera:
- grid_RRFS_NA_3km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1alpha
Fixes issue mentioned in #625
=> Add ulimit to the task scripts for Orion

ush/launch_FV3LAM_wflow.sh
The rocoto commands for the WCOSS dell and cray move from the launch script to the workflow environment files in the UFS SRW App like other machines.
WE2E tests on the WCOSS dell and cray:
- nco_grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
- MET_ensemble_verification
- https://github.com/ufs-community/ufs-srweather-app/pull/191
Fixes issue mentioned in #635
=> Move rocoto commands for WCOSS from launch script to env files

scripts/exregional_run_ensgridvx.sh, scripts/exregional_run_ensgridvx_mean.sh, scripts/exregional_run_ensgridvx_prob.sh, scripts/exregional_run_enspointvx.sh, scripts/exregional_run_enspointvx_mean.sh, scripts/exregional_run_enspointvx_prob.sh
The unchanged 'readlink' are renamed to "$READLINK" in the multiple task scripts for verification.
WE2E tests on the wcoss dell:
- MET_verification
- MET_ensemble_verification
Fixes issue mentioned in #637
=> Rename unchanged readlink in task scripts for verification

ush/config_defaults.sh, ush/setup.sh
Since RUN_CMD_FCST causes the warning of "-np: command not found", its expression in 'setup.sh' is changed.
WE2E tests on WCOSS Dell:
Fixes issue mentioned in #632
=> Fix -np warning by RUN_CMD_FCST

scripts/exregional_run_post.sh, ush/create_model_configure_file.sh, ush/templates/FV3.input.yml, ush/templates/input.nml.FV3, ush/templates/model_configure
- The template namelist files, 'input.nml' and 'model_configure', are updated for use of a newer version of the UFS Weather Model.
- The namelist parameter, print_diff_pgr, for the pressure tendency diagnostic is added to 'input.nml' (default = .false.).
WE2E tests on WCOSS dell and Hera:
- grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
- grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GSD_SAR
- grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
- ufs-community/ufs-srweather-app/pull/193
Fixes issue mentioned in #641 
@BenjaminBlake-NOAA, @MatthewPyle-NOAA
=> Update template namelist files for newer ufs weather model

scripts/exregional_run_fcst.sh
To avoid job failure, the number of tasks for the 'run_fcst' task is specified (with -n) on Orion.
WE2E test on Orion:
- grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km
Fixes issue mentioned in #647 
@JamesAbeles-NOAA
=> Specify the number of tasks for run_fcst on Orion

scripts/exregional_make_ics.sh, scripts/exregional_make_lbcs.sh, scripts/exregional_run_fcst.sh, tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km.sh, ush/config_defaults.sh, ush/generate_FV3LAM_wflow.sh, ush/setup.sh, ush/templates/FV3.input.yml, ush/templates/diag_table.FV3_GFS_v15_thompson_mynn_lam3km, ush/templates/field_table.FV3_GFS_v15_thompson_mynn_lam3km, ush/templates/input.nml.FV3, ush/valid_param_vals.sh
- Make the 'thompson_mynn_lam3km' ccpp suite, which is used at EMC, available in the regional workflow.
- Copy and link MERRA2 aerosol climatology data and lookup tables for optics properties.
and a new WE2E test on WCOSS dell and cray, and Hera:
- grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km
- ufs-community/ufs-srweather-app/pull/197
- Fixes issue mentioned in #643 
- Fixes issue mentioned in #579 
@BenjaminBlake-NOAA , @JiliDong-NOAA
=> Make thompson_mynn_lam3km ccpp suite available

scripts/exregional_run_fcst.sh
To avoid the failure of the 'run_fcst' task, the number of -N is set to PE_MEMBER01 in case of PE_MEMBER01<=24.
GST test on the WCOSS cray
Fixes issue mentioned in #654.
=> Fix APRUN issue on WCOSS cray

ush/retrieve_data.py, ush/templates/data_locations.yml
This tool is a stand alone script that can be used to grab external model files from a variety of sources including the internet, disk, and HPSS. The known locations for BDP AWS, HPSS, and NOMADS have been added here for demo purposes. It will also accept command line options to support user-defined disk locations with the caveat that file names provided on the command line must match the formatting necessary in the config file. A list of options for data_stores can be provided, and each will be checked until the required files are found. The list of known locations could easily be extended to add observation file locations for verification and data assimilation (future) purposes.
This tool has not yet been hooked into the workflow. I would like to receive feedback on the tool itself …
=> Add stand-alone Python data ingest tool.

.github/PULL_REQUEST_TEMPLATE, docs/UsersGuide/source/Chapter3.rst, update_fork.pl
Update NOAA-EMC/regional_workflow references to ufs-community/regional_workflow.  Remove user-defined reference to EMC_post in documentation.
Documentation updated to reflect changes to the regional_workflow.
=> Update NOAA-EMC/regional_workflow references to ufs-community/regional_workflow

scripts/exregional_run_post.sh
The SRW App cannot be run with the develop branch of UPP due to recent changes to use a fortran namelist (still called itag). For this PR changes are made to the exregional_run_post.sh script to account for this change.
Tests were conducted on Cheyenne and Hera for the Intel compiler. 6-hr long tests were successful on both.
Related to [#214](https://github.com/ufs-community/ufs-srweather-app/pull/214) for updating the UPP hash in the ufs-srweather-app to make use of these changes.
There are no documentation changes needed for SRW. Documentation related to this enhancement was updated internally in the UPP Users Guide.
Closes issue [207](https://github.com/ufs-community/ufs-srweather-app/issues/207) in ufs-srweather-app
=> Modify exregional_run_post to use the new UPP fortran namelist (itag) file

ush/generate_FV3LAM_wflow.sh, ush/get_crontab_contents.sh
When a user's `cron` table is empty, the `get_crontab_contents` function does not set the return variable properly due to a bug in the way `printf -v ...` is called towards the end of that function.  This PR fixes that bug as well as some others found after testing with an initially empty user cron table.
On Hera, Jet, and Cheyenne, ran the WE2E test `deactivate_tasks`, starting with both an empty `cron` table and a non-empty one.  All tests passed with the `cron` table being modified properly at the start and end of the test.
@chan-hoo pointed out this error on Hera.
=> Fix bug for crontab feature when user's cron table is empty

ush/machine/cheyenne.sh, ush/machine/hera.sh, ush/machine/jet.sh
Several paths in the machine-specific files point to locations in user paths or old locations of static data. This PR updates paths of static data in regional_workflow/ush/machine/ to point to the official, centralized locations on Cheyenne, Hera, and Jet.
Ran the following suite of end-to-end tests on Cheyenne and Jet prior to the latest ufs-weather-model hash update. All passed. This list of tests was chosen because all of these tests are known to succeed on all tested platforms, and this tests a variety of input and boundary condition types.
- grid_CONUS_25km_GFDLgrid_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
- grid_RRFS_CONUS_13km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
- grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
- …
=> Update locations of static data on Cheyenne, Hera, and Jet

ush/templates/model_configure
The format of `restart_interval` in `model_configure` was changed. Without the value of -1 next to the restart interval hours, restart files would be generated only once at the specific hour. To get restart files every restart interval hours, -1 should be added to the template.
WE2E tests:
- grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km
- MET_verification
- specify_RESTART_INTERVAL
=> Fix restart_interval in model_configure

ush/mrms_pull_topofhour.py
The ush/mrms_pull_topofhour.py script was modified to correct an issue with a hard-coded date. @JiliDong-NOAA discovered the issue and proposed a solution: change "20200304" to "20200303" in 4 places in the script, which will allow the script to properly copy MRMS obs on 03/03/2020 from /raw to /proc.
After the ush/mrms_pull_topofhour.py script was modified, dates on and surrounding 03/03/2020 were pulled as part of the GET_OBS_MRMS task. Checks were performed to make sure the data was pulled, reorganized, and renamed correctly, ensuring the changes were working as intended.
No changes to documentation are required.
Related to bug in issue #627 
Thanks to @JiliDong-NOAA for finding this bug and providing a solution.
=> Changed 20200304 to 20200303 in ush/mrms_pull_topofhour.py

ush/templates/parm/metplus/EnsembleStat_conus_sfc.conf, ush/templates/parm/metplus/EnsembleStat_upper_air.conf, ush/templates/parm/metplus/PointStat_conus_sfc.conf, ush/templates/parm/metplus/PointStat_conus_sfc_mean.conf, ush/templates/parm/metplus/PointStat_conus_sfc_prob.conf, ush/templates/parm/metplus/PointStat_upper_air.conf, ush/templates/parm/metplus/PointStat_upper_air_mean.conf, ush/templates/parm/metplus/PointStat_upper_air_prob.conf
Beginning with METplus 4.1, MET 10.1, observations can be filtered by a list of quality marks in PointStat and EnsembleStat, rather than a simple threshold value as used in PB2NC. This PR changes to make use of this option in the METplus configuration files updated in #695. Default values of 0,1,2,3,9 are used, avoiding prepbufr quality marks 4-8.
WE2E tests MET_ensemble_verification and MET_verification passed on hera. If an earlier version of MET/METplus is used, the new options are passed over.
=> Verification task include-list quality mark options

modulefiles/tasks/gaea/make_grid.local, modulefiles/tasks/gaea/make_ics.local, modulefiles/tasks/gaea/make_lbcs.local, modulefiles/tasks/gaea/run_fcst.local, modulefiles/tasks/gaea/run_vx.local, ush/config_defaults.sh, ush/generate_FV3LAM_wflow.sh, ush/machine/gaea.sh, ush/templates/FV3LAM_wflow.xml, ush/valid_param_vals.sh
Add machine specific files to allow the SRW app E2E tests to run successfully on Gaea. These changes include adding a <native> section to the FV3LAM template that specifies a cluster for slurm. This addition is required on Gaea and is not currently supported out of the box by Rocoto. Other machine specific files have been added as well.
E2E tests below have been run successfully with the intel (18)/intelmpi on Gaea
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
grid_RRFS_CONUS_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha
Add any links to external PRs. For example:
- ufs-community/ufs-srweather-app/pull/<236>
- https://github.com/ufs-community/ufs-srweather-app/issues/<235>
=> Add Gaea as a supported platform for the regional_workflow

ush/generate_FV3LAM_wflow.py, ush/get_crontab_contents.py, ush/retrieve_data.py, ush/setup.py
- Fix typo in 'setup.py'.
- Fix crontab issue on wcoss_dell_p3 in the workflow python scripts.
- Remove capture_output as PR #744.
- 6h GST tests with FV3GFS_v15p2 and FV3GFS_v16 on wcoss_dell_p3
=> Fix typo and crontab issue on wcoss dell in workflow python scripts

tests/WE2E/run_WE2E_tests.sh, ush/config_defaults.sh, ush/config_defaults.yaml, ush/launch_FV3LAM_wflow.sh, ush/load_modules_run_task.sh, ush/setup.py, ush/setup.sh
Since 'env' was replaced with 'modulefiles' in https://github.com/ufs-community/ufs-srweather-app/pull/238, the counterpart in the regional workflow should be updated.
- GST 6h test on WCOSS_DELL_P3 with both bash and python.
- WE2E test on WCOSS_DELL_P3:
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km
=> Replace env with modulefiles in scripts

.github/CODEOWNERS
Make the following modifications to the github `CODEOWNERS` file:
1) Add several EPIC staff (@gspetro-NOAA, @natalie-perlin, and @EdwardSnyder-NOAA) so they are notified of all PRs and can review them.
2) Remove duplicate entries.
3) Remove users who will no longer be working with the repo (thus far only @jwolff-ncar) .
None.
=> Modifications to `CODEOWNERS` file

tests/WE2E/create_WE2E_resource_summary.py
Addresses Issue #768.
Adds a utility that summarizes Rocoto database computational usage information.
The utility runs on the command line, and prints a report to the screen. It is left to the user to pipe this output to a file for saving, if that is desired.
An example of the output from a previous set of tests run on Jet:
```
$ python create_WE2E_resource_summary.py -e /mnt/lfs1/BMC/wrfruc/cholt/repos/expt_dirs -n 'grid*' 'nco*'
--------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------
Core Hours  |  Run Time (mins)
-------------------------------------------------------------------------------------------------------------- …
```
=> Adding a python utility for summarizing compute.

ush/config.nco.sh
The sample script for the NCO mode `config.nco.sh` is updated.
- Sample script run
=> Update sample script for NCO mode

ush/get_crontab_contents.sh
The E2E tests are removing pre-existing lines from crontab on Cheyenne and overwriting others. Apparently, Cheyenne previously added 3 additional lines to the output of crontab -l, but after the upgrade, this is no longer the case. The extra logic in get_crontab_contents.sh to start counting lines after 3 on cheyenne has been removed and the E2E tests are now functioning as expected.
=> removed cheyenne-specific crontab editing section

ush/machine/gaea.sh
Updated staged data file path for Gaea to a common location.
Ran three (`grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16`,  `grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16`,  `grid_SUBCONUS_Ind_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16`) e2e tests on Gaea successfully. 
None.
No documentation changes are required.
=> update staged data dir

ush/machine/macos.sh
A machine file for the MacOS system has been added. It sets the location of stationary datasets (fix/) on a system, an option to set the external model data location, run commands for executables, architecture information.
Built and run a 12-h or 48-h test was for the case of 20190615 on two MacOS systems, with M1/arm64 and Intel/x86_64 architectures. 
- HPC-stack needs to be built for the same MacOS system, compilers, MPI, modules.
- ufs-srweather-app needs to be configured for the MacOS (modulefiles)
Documentation for the SRW build on MacOS is updated
This PR expands a list of systems that are supported by the SRW
=> Added a machine file for MacOS

modulefiles/tasks/cheyenne/run_vx.local, modulefiles/tasks/hera/run_vx.local, modulefiles/tasks/wcoss_dell_p3/run_vx.local, ush/machine/cheyenne.sh, ush/machine/hera.sh, ush/machine/orion.sh, ush/machine/wcoss_dell_p3.sh, ush/templates/parm/metplus/EnsembleStat_conus_sfc.conf, ush/templates/parm/metplus/EnsembleStat_upper_air.conf, ush/templates/parm/metplus/PointStat_conus_sfc.conf, ush/templates/parm/metplus/PointStat_conus_sfc_mean.conf, ush/templates/parm/metplus/PointStat_conus_sfc_prob.conf, ush/templates/parm/metplus/PointStat_upper_air.conf, ush/templates/parm/metplus/PointStat_upper_air_mean.conf, ush/templates/parm/metplus/PointStat_upper_air_prob.conf
Updated machine files to use MET 10.1.0 and METplus 4.1.0 and removed unused module loads from modulefiles. The update in versions allows use of ENSEMBLE_STAT_OBS_QUALITY_INC which is now used and updated to include "NA" to capture observations not using quality marks. Obs BUFR list and map is also updated to use MET-derived variables.
Note, this PR is for the ens_design_RRFS branch.
Addresses #754 and #696.
=> [ens_design_RRFS] Update to MET/METplus configuration and versions

tests/WE2E/get_WE2Etest_names_subdirs_descs.sh
This PR fixes a bug in the way the number of time steps (`num_time_steps` in `get_WE2Etest_names_subdirs_descs.sh`) is calculated for each WE2E test when creating the CSV file containing information about the available WE2E tests.
Reran the `run_WE2E_tests.sh` script (which in turn calls `get_WE2Etest_names_subdirs_descs.sh`), and a CSV file containing the adjusted numbers was successfully created.
None needed.
=> Bug fix for calculation of number of time steps for each WE2E test

modulefiles/tasks/noaacloud/make_grid.local, modulefiles/tasks/noaacloud/make_ics.local, modulefiles/tasks/noaacloud/make_lbcs.local, modulefiles/tasks/noaacloud/make_orog.local, modulefiles/tasks/noaacloud/make_sfc_climo.local, modulefiles/tasks/noaacloud/run_fcst.local, modulefiles/tasks/noaacloud/run_post.local
Update the Spack Stack location for noaacloud in modulefiles/tasks. 
A subset of the quick tests (see below) were ran in the Jenkins pipeline for AWS, Azure, and GCP. All tests ran successfully to completion. 
`grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16`
`grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16`
`grid_SUBCONUS_Ind_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16`
None.
No documentation changes are needed.
@natalie-perlin @gspetro-NOAA @mark-a-potts @ulmononian Bruce Kropp
=> Update Spack Stack Location

ush/machine/hera.sh
This is a bug fix for running the WE2E tests on Hera. The existence of this path is causing failures after the path has become unreadable.
Tested as a part of another branch. Will run through auto-tests here to test fully.
The code won't pass the build tests without [PR #23](https://github.com/ufs-community/ufs-srweather-app/pull/323) in SRW.
=> Remove un-readable path to system dir on Hera.

modulefiles/tasks/jet/run_vx.local, ush/machine/jet.sh
Added MetPlus file paths to the Jet machine file in the develop branch. A similar PR #797 was approved for the release branch.
Ran `MET_verification` and `MET_ensemble_verification` successfully on Jet.
None.
No documentation changes are needed.
=> [develop] Add MET/METplus to Jet

scripts/exregional_make_grid.sh
This fixes a typo in exregional_make_grid.sh. The variable referenced should be ${rgnl_grid_nml_fp}, but the "l" was missing. This throws errors on some platforms due to unbound variables.
=> fixed typo in exregional_make_grid.sh

ush/launch_FV3LAM_wflow.sh, ush/load_modules_run_task.sh
Machine file wrapper `source_machine_file.sh` uses `save/restore_shell_opts` but those are not defined when it is called from 
`load_module_run_task` and `launch_FV3LAM_wflow` because bash utilities are sourced after the machine file.
A simple change in order of sourcing these files should fix it. After this fix, i was able to use `set -e` for all scripts.
Run one test on hera manually, will run automated test later.
=> Bugfix with machine file wrapper.

ush/machine/gaea.sh
Recent versions of MET/METplus were installed on Gaea (https://dtcenter.org/community-code/metplus/metplus-4-1-existing-builds). This PR adds theirs paths to the Gaea machine file, which should enable their use in the workflow.
`MET_ensemble_verification` and `MET_verification` tests need to be run on Gaea by someone with access to the platform and it needs to be confirmed that observations are staged in /lustre/f2/pdata/ncep_shared/UFS_SRW_App/develop/obs_data. Other platforms should not be impacted.
Once this is successfully tested and merged, @jessemcfarland should be able to remove the logic in https://github.com/ufs-community/ufs-srweather-app/pull/333 that avoids running the verification tests on Gaea.
=> Use new MET/METplus installs on Gaea
