jobs/JFV3CAM_NEST_ENVIR, jobs/JFV3CAM_SAR_ENVIR, rocoto/drive_fv3nest.xml, rocoto/drive_fv3nest_retro.xml, rocoto/drive_fv3sar.xml, rocoto/drive_fv3sar_retro.xml, rocoto/drive_fv3sar_template.xml
export GESROOT=${maindir}/${gesdir}/${USER}/nwges
For running on WCOSS only: FV3GFS-T2O has been changed to HREF-T2O
=> Update GESROOT in ENVIR J-jobs

ush/make_ICS_surf_LBC0.sh, ush/make_grid_orog.sh
=> Remove unneeded link commands and add comments.

modulefiles/fv3sar_workflow/orog.odin, regional/build_regional, sorc/global_equiv_resol.fd/Makefile_odin, sorc/mosaic_file.fd/Makefile_odin, sorc/regional_grid.fd/Makefile_odin, ush/fv3gfs_filter_topo.sh, ush/make_grid_orog.sh, ush/setup.sh, ush/templates/wrtcomp_CLUE
1. Added building scripts for all programs on Odin;
2. Fixed directory names for Odin;
3. Fixed a bug in make_grid_orog.sh, where "n_del2_weak" for program **filter_topo** expects an integer value.
=> Added support on Odin, tested and fixed make_grid_orog.sh

jobs/JREGIONAL_MAKE_SFC_CLIMO, scripts/exregional_make_ic_lowbc.sh, scripts/exregional_make_lbc1_to_lbcn.sh, scripts/exregional_make_sfc_climo.sh, ush/process_args.sh, ush/source_funcs.sh, ush/stage_static.sh, ush/templates/FV3SAR_wflow.xml
Checked for bit-for-bit identical results with previous version.
=> Community develop

scripts/exfv3cam_sar_chgres.sh, scripts/exfv3cam_sar_fcst.sh, ush/global_chgres.sh
Hi Eric, I've added your fix for the BC job to the chgres run script.  If it looks good to you we'll merge it into the develop branch.  I'm not sure why the changes to the forecast run script and global_chgres.sh are showing up again, those were already committed to develop.  Maybe I forgot to update my fork.
=> Fix to BC processing for FV3SARDA

jobs/JREGIONAL_GSIANL, jobs/JREGIONAL_GSIANL_FIRSTGUESS, scripts/exregional_gsianl.sh, scripts/exregional_gsianl_firstguess.sh
Hi Eric, I've updated COMINrtma in the GSI J-jobs.  I've also removed COMINnam from the J-jobs and ex-scripts since COMINrap is used instead.
=> Fix COMINrtma path and remove COMINnam path from GSI jobs

jobs/JREGIONAL_ENVIR, modulefiles/hera/fv3, modulefiles/hera/regional, rocoto/rocoto_pre_job.sh, rocoto/run_regional_hera.sh, rocoto/sites/hera.ent, sorc/build_forecast.sh, sorc/link_fix.sh, sorc/machine-setup.sh
I was able to run a successful forecast on Hera.  These are the first set of changes for porting the develop branch of the regional workflow to Hera.  The namelist and model configure file changes haven't been committed yet because I am going to restructure the forecast run script to add certain values to template files rather than trying to maintain many separate versions of files in parm.  New files include rocoto/run_regional_hera.sh, rocoto/sites/hera.ent, and modulefiles/hera/fv3.  Compiling the code might not work right just yet, I had to follow specific instructions from Jim to get it to work.  More changes will be coming but let me know if you have any suggestions for what I've done so far.
=> First set of changes for port to Hera

jobs/JREGIONAL_ENVIR, parm/input_sar_ak.nml, parm/input_sar_conus.nml, parm/input_sar_conus_ccpp.nml, parm/input_sar_guam.nml, parm/input_sar_hi.nml, parm/input_sar_pr.nml, parm/model_configure_sar.tmp_ak, parm/model_configure_sar.tmp_conus, parm/model_configure_sar.tmp_guam, parm/model_configure_sar.tmp_hi, parm/model_configure_sar.tmp_pr
A new section has been added to the namelists.  Also, the path to NDATE and NHOUR on Hera was updated in JREGIONAL_ENVIR.
=> Changes to run with latest NEMSfv3gfs master code

CODEOWNERS
=> Add CODEOWNERS file with Julie, Mike, Gerard and Jeff as owners.

CODEOWNERS
No tests run since the workflow/scripts are unaffected by this PR.
=> Change CODEOWNERS to correct my GitHub account name and add Jamie

ush/get_extrn_mdl_file_dir_info.sh, ush/set_extrn_mdl_params.sh, ush/set_predef_grid_params.sh, ush/valid_param_vals.sh
=> Mods to update real-time data on Jet and update pre-defined Alaska domains/GFDLgrid option for GSD 3-km CONUS domain

scripts/exregional_make_grid.sh
=> Remove Jet module load stanza in exregional_make_grid.sh

ush/Python/plot_allvars.py
This Python script creates plots of the following variables with FV3SAR grib2 output:
Sea level pressure
2-m temperature
2-m dew point temperature
10-m wind speed
Surface-based CAPE/CIN
500-mb heights/winds/vorticity
250-mb wind speed
Total precipitation
Composite reflectivity
Max/Min Hourly 2-5 km Updraft Helicity
It was originally written in Python 2 but was converted to Python 3 and tested on Hera.
=> Add Python plotting script for FV3SAR grib2 output

README.md
Fixes to README.md suggested by @RatkoVasic-NOAA after trying out PR #212.
1) Print newlines before step 4 and step 5 so that they show up as separate entries in the list.
2) Need a link to the User's Guide in step 4.  @JulieSchramm, @mkavulich, @jwolff-ncar, where should we point users to?
=> Edit README.md.

update_fork.pl
Updating the update_fork.pl script for user forks to update the develop branch (which is now the default) rather than community_develop
Updated my own fork using the new version of this script
=> Update the update_fork.pl script for the new develop branch

ush/templates/FV3SAR_wflow.xml, ush/templates/README.xml_templating.md
I added a README combining some of the information-gaps gleaned from conversations with others who wish to add to and modify the Rocoto XML template, and a docstring in the template to describe what it is, how it's filled in, and where to find additional information.
No tests were conducted.
This material was greatly improved by feedback received from @jwolff-ncar.
=> Adding docs for Rocoto Jinja template.

ush/Python/env.yaml, ush/Python/plot_allvars.py
This is an updated version of the Python plotting script for the UFS SRW app.  The script now uses the argparse library, reads in an env.yaml file (currently blank), defines the location of the input grib2 file with placeholders (they will need to be read in somehow), and uses cartopy instead of basemap.  I have never used cartopy before and I think the plots definitely need to be improved but this was a first attempt.  If anyone knows more about cartopy than I do (which is very little!) please feel free to update/adjust accordingly.
None required.
=> Updated Python plotting script for UFS SRW app

scripts/exregional_make_grid.sh, scripts/exregional_make_ics.sh, scripts/exregional_make_lbcs.sh, scripts/exregional_make_orog.sh, scripts/exregional_run_post.sh, ush/generate_FV3LAM_wflow.sh, ush/setup.sh
Applying the changes necessary for cmake build to release branch. PR #304 took care of this for the develop branch. This version omits the commits that were included in that PR for back-compatibility with old build system: the release branch will only support cmake builds going forward.
Ran build and end-to-end tests on Cheyenne for Intel. Ran build and end-to-end tests on Hera for Intel.
=> Applying necessary cmake build changes to release branch

scripts/exregional_make_orog.sh, scripts/exregional_run_fcst.sh, tests/run_experiments.sh, ush/config_defaults.sh, ush/link_fix.sh, ush/setup.sh, ush/templates/FV3.input.yml
Removed checks on the RRFS_v1beta SDF implemented for use with the GSL GWD suite (now uses the GFS GWD suite).  No longer copies staged orography files necessary for the GSL GWD suite.  
Runs to completion on Hera.
=> RRFS_v1beta SDF changes after reverting from GSL to GFS GWD suite

scripts/exregional_make_ics.sh, ush/config.community.sh, ush/setup.sh
Point exregional_make_ics.sh script to the new location for geogrid files (fix_am directory).
Set the config.community.sh external model staging user-defined variable to "false."
Tested on Jet.
@KateFriedman-NOAA
=>  Release branch: Point exregional_make_ics.sh script to the new location for geogrid files (fix_am directory)

scripts/exregional_run_post.sh
Change the tmmark from tm${cyc} to tm00.
=> Modification to tmmark

scripts/exregional_run_post.sh, ush/templates/input.nml.FV3
Fixed missing changes to namelist to get stochastic physics working.  Changed the tmmark in the post ex-script from tm${fhr} to tm00. 
Tested on both Jet and Hera.
=> Fix stochastic physics namelist block.  Change tm${cyc} to tm00.

ush/Python/plot_allvars.py, ush/Python/plot_allvars_diff.py
Output files generated by plot_allvars and plot_allvars_diff are now written out to the expt_dir rather than the Python directory under regional_workflow/ush/Python.  In addition, logic has been added to generate plots for a defined set of forecast hours.  The user must now specify the starting/ending forecast hours as well as the forecast hour increment.
These changes were tested on both Hera and Jet.
Resolves issue #376 : https://github.com/NOAA-EMC/regional_workflow/issues/376
Ben Blake, David Wright
=> Enhancements to Python plotting scripts

ush/Python/sq_job.sh, ush/Python/sq_job_diff.sh
With the updates to the python scripts to run multiple forecast hours and several variables, it is necessary to submit as a batch script. These are sample slurm submission scripts.
Tested and run on Hera only at this point. These need to be ported and expanded for other machines. (For example, should also create sample qsub scripts for Cheyenne prior to the release)
We will also want to include this in the release branch.
Related to https://github.com/NOAA-EMC/regional_workflow/pull/381
@BenjaminBlake-NOAA @dmwright526 @christinaholtNOAA
=> Add submission scripts for python scripts for hera specifically

ush/Python/plot_allvars.py, ush/Python/plot_allvars_diff.py, ush/Python/sq_job.sh, ush/Python/sq_job_diff.sh
Output files generated by plot_allvars and plot_allvars_diff are now written out to the expt_dir rather than the Python directory under regional_workflow/ush/Python. In addition, logic has been added to generate plots for a defined set of forecast hours. The user must now specify the starting/ending forecast hours as well as the forecast hour increment.  These changes have been merged into the develop branch, but also need to be added to the release branch.
These changes were tested on both Hera and Jet.
Resolves issue [376](https://github.com/NOAA-EMC/regional_workflow/issues/376)
David Wright, Jamie Wolff
=> Add enhancements to Python plotting scripts to release branch

ush/generate_FV3LAM_wflow.sh, ush/templates/input.nml.FV3
Remove namelist entries referencing SPP until code is ready in authoritative ufs-weather-model repo.
Tested successfully on Hera.
@gsketefian
=> Remove SPP from input.nml.FV3 template until code is ready in ufs-weather-model.

ush/launch_FV3LAM_wflow.sh
Same as #437 but for the develop branch.
The tasks are submitted without any conflicts and warnings on Orion.
Fixes issue mentioned in #436
=> Add 'module purge' to the launch script for orion (develop)

LICENSE.md, ush/Python/plot_allvars.py, ush/Python/plot_allvars_diff.py, ush/Python/qsub_job.sh, ush/Python/qsub_job_diff.sh
Pulling changes for python plotting made only in the release branch back to develop now that things have settled down. 
Also adding the LICENSE.md file that was added to release.
Test using CONUS_25km_GFSv15p2 was conducted on hera, including plotting, and all looked good.
=> Updating develop branch with updates from the release branch 

scripts/exregional_get_mrms_files.sh
Fixed a couple typos and modified syntax for status message to work correctly in exregional_get_mrms_files.sh to account for file names with either gyre or tide in them. 
Test conducted on hera to pull the data ran successfully
Fixes issue mentioned in https://github.com/NOAA-EMC/regional_workflow/issues/462
@michelleharrold
=> Bug fix for MRMS data pull script [to develop branch]

.github/CODEOWNERS
Update the CODEOWNERS file for new code review members.
=> Update CODEOWNERS file for new code reviewers

tests/WE2E/run_WE2E_tests.sh
Another machine based logic was found and is removed from the we2e script. I apologize for this.
Link to https://github.com/ufs-community/regional_workflow/pull/713
=> Quick bug fix: remove machine based logic

modulefiles/tasks/hera/get_obs.local, modulefiles/tasks/hera/miniconda_regional_workflow, tests/WE2E/setup_WE2E_tests.sh
Pin down the version of miniconda3 on Hera, and do not append to the module path. Addresses Issue https://github.com/ufs-community/ufs-srweather-app/issues/256.
Command line tests for loading modules.
Should be tested and merged with SRW [PR #257](https://github.com/ufs-community/ufs-srweather-app/pull/257)
Addresses the SRW Issue [#256](https://github.com/ufs-community/ufs-srweather-app/issues/256)
@danielabdi-noaa @JeffBeck-NOAA
=> Pin down hera miniconda3 module file version.

ush/machine/jet.sh
Added MetPlus file paths to the Jet machine file.
Ran `MET_verification` and `MET_ensemble_verification` successfully on Jet via the Jenkins pipeline.
None.
No changes to the documentation are expected.
=> [release] Adding METplus file paths to Jet

ush/machine/linux.sh
Added a machine file template for Linux, under ./ush/machine
@gspetro-NOAA
=> add a linux.sh machine file (a template)

scripts/exregional_make_ics.sh, scripts/exregional_make_lbcs.sh
removing fix_dir_input_grid from namelist variables.
=> [release/public-v2] removed namelist variables
